---
- name: Check to see if dbndns is already installed
  stat:
    path={{ tinydns_config_path }}
  register: dbndns_configured

- name: Install dbndns packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    install_recommends=no
    cache_valid_time=1800
  with_items:
  - dbndns
  - daemontools
  - daemontools-run
  - ucspi-tcp

- name: Create tinydns groups
  group:
    name={{ item }}
    system=yes
  with_items:
    - "{{ tinydns_user }}"
    - "{{ dnscache_user }}"

- name: Create tinydns users
  user:
    name={{ item }}
    group={{ item }}
    home=/nonexistent
    shell=/bin/false
    system=yes
  with_items:
    - "{{ tinydns_user }}"
    - "{{ dnscache_user }}"

- name: Ensure svscan is running
  service:
    name=svscan
    state=started
    enabled=yes

- name: Setup tinydns
  command: >
    tinydns-conf {{ tinydns_user }} {{ tinydns_group }} {{ tinydns_config_path }} {{ tinydns_bind_address }}
  when: not dbndns_configured.stat.exists

- name: Create tinydns log directory
  file:
    path=/var/log/tinydns
    owner={{ tinydns_user }}
    group={{ tinydns_group }}
    state=directory

- name: Change tinydns log directory configuration
  file:
    path={{ tinydns_config_path }}/log/main
    state=absent
    force=yes

- name: Change tinydns log directory configuration
  file:
    dest={{ tinydns_config_path }}/log/main
    src=/var/log/tinydns/
    state=link

- name: Create tinydns link for service daemon
  file:
    src={{ tinydns_config_path }}
    dest=/etc/service/tinydns
    state=link
